[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
PYTHON_VERSION = "3.11"
PORT = "3002"
LOG_LEVEL = "INFO"
ENVIRONMENT = "production"
JOB_BATCH_SIZE = "10"
QUEUE_POLL_INTERVAL = "200"
OPENAI_MODEL = "gpt-4"
OPENAI_MAX_TOKENS = "1000"
OPENAI_TEMPERATURE = "0.7"
TELEGRAM_MESSAGE_QUEUE = "telegram_received_messages"
BOT_RESPONSE_QUEUE = "telegram_bot_responses"
QUEUE_VISIBILITY_TIMEOUT = "30"
QUEUE_MAX_RETRIES = "3"
