version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: expensio-postgres
    environment:
      POSTGRES_USER: expensio_user
      POSTGRES_PASSWORD: expensio_password
      POSTGRES_DB: expensio
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./supabase/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U expensio_user -d expensio"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - expensio-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: expensio-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: expensio_user
      RABBITMQ_DEFAULT_PASS: expensio_password
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - expensio-network

volumes:
  postgres_data:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  expensio-network:
    driver: bridge
